local editor = require('distant.editor')
local fn = require('distant.fn')
local match = require('luassert.match')
local stub = require('luassert.stub')
local v = require('distant.internal.vars')

describe('editor.open', function()
   it('should fail is path is not a string', function()
      assert.has.error(function()
         editor.open(123)
      end, 'path must be a string')
   end)
 end)
