return {
    auth         = require('distant-core.auth'),
    builder      = require('distant-core.builder'),
    Client       = require('distant-core.client'),
    Cli          = require('distant-core.cli'),
    data         = require('distant-core.data'),
    Destination  = require('distant-core.destination'),
    EventEmitter = require('distant-core.emitter'),
    installer    = require('distant-core.installer'),
    log          = require('distant-core.log'),
    Manager      = require('distant-core.manager'),
    Server       = require('distant-core.server'),
    settings     = require('distant-core.settings'),
    ui           = require('distant-core.ui'),
    utils        = require('distant-core.utils'),
    vars         = require('distant-core.vars'),
    Version      = require('distant-core.version'),
}
